apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp-custom # <--- Inna nazwa Deploymentu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-app      # <--- Inna etykieta niż wcześniej, więc musi być zgodna z template.metadata.labels
  template:
    metadata:
      labels:
        app: custom-app     # <--- Inna etykieta niż wcześniej, więc selektor w Servisie też musi być inny
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: website-volume
              mountPath: /usr/share/nginx/html  # <--- Nadpisujemy ten katalog w kontenerze
      volumes:
        - name: website-volume
          configMap:
            name: my-website-config         # <--- Bierzemy pliki z naszej ConfigMapy