apiVersion: v1
kind: Pod
metadata:
  name: pod-z-dyskiem
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html" # Gdzie zamontować w środku
          name: moj-vol
  volumes:
    - name: moj-vol
      persistentVolumeClaim:
        claimName: moje-zlecenie-pvc # <--- Podpinamy nasze zlecenie - tj. Nazwa naszego PVC w pliku zlecenia PVC:  1-pvc-dynamic.yaml