apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: default
type: Opaque
data:
  # To jest zakodowane base64: "admin:$apr1$KqVj... (zahaszowane 'tajne123')"
  auth: YWRtaW46JGFwcjEkcFFuODR2Y2QkQlAuLnNvbWxvLm1hLnAvLnRTLmVwMAo=