apiVersion: v1
kind: Service
metadata:
  name: ingress-service
  namespace: ingress-space
spec:
  type: LoadBalancer  # <--- ZMIANA: Z NodePort na LoadBalancer
  ports:
    - port: 80        # <--- Nasłuchujemy na głównym porcie HTTP
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443       # <--- Nasłuchujemy na głównym porcie HTTPS
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    name: nginx-ingress