apiVersion: v1
kind: Namespace
metadata:
  name: ingress-space
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-space
data:
# Tutaj instruktor mówił, że może być pusto, ale w przyszłości
# możemy tu dodać np. 'ssl-protocols' czy 'log-format'.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-serviceaccount
  namespace: ingress-space