apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  namespace: ingress-space
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-ingress
  template:
    metadata:
      labels:
        name: nginx-ingress
    spec:
      serviceAccountName: ingress-serviceaccount # Łączymy z kontem z kroku 1
      containers:
        - name: nginx-ingress-controller
          # Obraz wspomniany w szkoleniu (może być nowszy, ale to ten z przykładu)
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.21.0
          args:
            # Instruktor mówi, że trzeba wskazać Nginxowi jego plik konfiguracyjny
            - /nginx-ingress-controller
            - --configmap=$(POD_NAMESPACE)/nginx-configuration
          env:
            # To są te zmienne środowiskowe, o których mowa w 11:45
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443