apiVersion: v1
kind: PersistentVolume
metadata:
  name: manualny-pv-500m
spec:
  storageClassName: manual  # <--- Wymyślona nazwa klasy (ważne!)
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete  # Domyślnie jest Delete - cyzli jak usuwasc PVC to i PV ginie i dupa
  hostPath:
    path: "/tmp/data-manual" # Ścieżka wewnątrz kontenera k3s-master