apiVersion: v1
kind: PersistentVolume
metadata:
  name: bezpieczny-dysk-pv
spec:
  storageClassName: manual-safe  # Nowa nazwa klasy
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # <--- TO JEST KLUCZ! (Domyślnie jest Delete)
  hostPath:
    path: "/tmp/dane-bezpieczne" # Fizyczne miejsce w kontenerze