apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  containers:
    - name: shell
      image: alpine
      command: ["sleep", "3600"] # Niech sobie wisi i czeka
      env:
        - name: MOJE_HASLO_DO_BAZY  # <--- Nazwa zmiennej w systemie
          valueFrom:
            secretKeyRef:
              name: db-passwords    # <--- Nazwa sekretu w K8s
              key: DB_PASSWORD      # <--- Klucz wewnątrz sekretu