---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: molecule_local/dhcp-test:latest
    pre_build_image: false
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
