apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim # tutaj tworzymy PVC
spec:
  accessModes:
    - ReadWriteOnce   # Dysk może być podpięty tylko do jednego NOD'a na raz
  resources:
    requests:
      storage: 1Gi    # Wielkość dysku, którą żądamy